### ISSUE TITLE
GPS ile konum bilgisinden en yakın kuruluşlar listesi 

### ISSUE THREAD

**Issue by selamikarakas** [acikkaynak/eczane-frontend#104]
GPS'ten alınan konumu ile en yakın hizmet görmek isteyen kullanıcı için bir buton olsun. Kullanıcı butona tıklarsa izin için browser pop-up'ı çıksın. Bu pop-up çıkmadan önce kullanıcıya onay için yönlendirileceği ve onaylaması gerektiği söylensin. 

Onaydan sonra her sağlık kuruluşu çeşidinden en az bir tane gösterecek şekilde haritaya zoom girilsin. Liste görünümünde de gerekli filtre uygulansın. En yakın olanın rengi değişebilir veya yanıp sönebilir.

Eğer kullanıcı filtreleme yaparsa sadece filtre'deki kuruluş çeşidi görünsün ve ona göre tekrar zoom in yapılsın. liste görünümünde de filtreleme uygulansın

**Comment by okazkayasi** [comment]
#122'ye taşındı
