### ISSUE TITLE
bug: data that doesn't show up when not zoomed in

### ISSUE THREAD

**Issue by selamikarakas** [acikkaynak/eczane-frontend#11]
Bazı yerlerde data'lar kümelendiği için zoom girmeden data görünmüyor. Mesela kahramanmaraş merkez data'ları ben baktığımda 3 tane olmasına rağmen zoom girmeden görünmüyordu.

**Comment by unitythemaker** [comment]
Daha fazla detay verebilir misiniz? Aynı problemi biz yaşamadık da.

**Comment by selamikarakas** [comment]
Umarım bu iki ekran görüntüsü açıklayabilmiştir kastettiğimi.
![image](https://user-images.githubusercontent.com/57862307/218282727-818e635b-f0c3-4b0c-a3a0-1874ac05dc41.png)

![image](https://user-images.githubusercontent.com/57862307/218282718-a9f1e6b3-339b-4ed1-8bd8-0620d381926a.png)

**Comment by cagan123-alt** [comment]
Probleme baktım tekrardan ama anlayamadım.MarkerCluster yapıldı orada 3 tane daha marker olduğunu zoomlandığında gösteriliceğini yapılması amacıyla kullanıcı 3'e tıkladığında ya da zoomladığında çıkıyo markerlar onun zaten öyle olması gerekiyor.Yoksa uzaktan bakıldığında zaten markerın nerede olduğu belli olmaz.Yanlış anlamışta olabilirim.Yanlış anladığımı düşünüyorsanız.Tekrardan belirtir misiniz tam problemi.

**Comment by selamikarakas** [comment]
dediğini anladm. clustering'in user friendly bir şekilde yapılmadığını düşünüyorum. Kahramanmaraş merkez ve Adıyaman merkez 'in tam ortasında 7 var. zoom girince bunlar bölünüyor. şehirlerin kendi içinde cluster olması gerektiğini düşünüyorum.
