### ISSUE TITLE
Safari Lock Butonu

### ISSUE THREAD

**Issue by okazkayasi** [acikkaynak/eczane-frontend#111]
<img width="1291" alt="image" src="https://user-images.githubusercontent.com/10429728/218740488-ddd6d1a7-cdff-4e93-9dd7-4f1e25207bd8.png">

**Comment by egekaradibak** [comment]
Selam, bakan yoksa yardimci olabilirim

**Comment by okazkayasi** [comment]
Harika olur @egekaradibak. Onaylarsanız in-progress'e alayım

**Comment by egekaradibak** [comment]
tamamdir super

**Comment by egekaradibak** [comment]
sadece biraz daha bilgi verebilirseniz bir de bug hakkinda cok iyi olur

**Comment by okazkayasi** [comment]
<img width="776" alt="image" src="https://user-images.githubusercontent.com/10429728/219785161-b9a356e0-d26e-43e6-9e10-f8bb87efa110.png">

<img width="776" alt="image" src="https://user-images.githubusercontent.com/10429728/219785291-e3a9a821-c25c-4c14-ab8b-cadfdfdca872.png">

Lock icon'u ikinci image'deki gibi olsun istiyoruz. @egekaradibak

**Comment by okazkayasi** [comment]
@egekaradibak svg optimization issue'su bu sorunu da çözmüş durumda. Bunu da ready-for-testing'e alıyorum
