### ISSUE TITLE
Material UI'ların module.scss'e aktarılması

### ISSUE THREAD

**Issue by okazkayasi** [acikkaynak/eczane-frontend#113]
Material UI, emotion'la ve normal css'le verilen styling'lerin aktarılması. Buna subtask'lar gelecek

**Comment by furkanevin** [comment]
module.scss e aktarılmalı diye düşünüyorum

**Comment by okazkayasi** [comment]
module.scss diye duzelttim. module scss support'u projeye eklendi

**Comment by okazkayasi** [comment]
Subtasklar Asagidaki Gibi: 
--------------------------------------------------------------
- src/components/Footer/Footer.js -> style.css dosyasi var bunun. ayni zamanda emotion da var. ikisinin de module.scss'e aktarilmasi. src/components/ListPage.js -> module.scss'e aktarilmasi. Bu ikisi bir task.

- src/components/Header/HeaderCombined.js -> Burada Header'a dair 5-6 dosya mevcut. Bu subtask hepsinin module.scss'e aktarilmasi.

- src/components/MainViewContainer/MainViewContainer.js -> emotion ve MUI mevcut.

- src/components/InfoCard.js -> MUI -> module.scss'e

**Comment by okazkayasi** [comment]
LıstPage.js bende

**Comment by burakkp** [comment]
Bunu ben aldim. src/components/InfoCard.js -> MUI -> module.scss'e

**Comment by ygzaydn** [comment]
MainViewContainer için değişikleri yapıyorum.

**Comment by mehmetkursataydin** [comment]
src/components/Header/HeaderCombined.js -> Burada Header'a dair 5-6 dosya mevcut. Bu subtask hepsinin module.scss'e aktarilmasi.

Buna bakiyorum.
