### ISSUE TITLE
City buttons are smaller than it should be in the mobile devices

### ISSUE THREAD

**Issue by furkanevin** [acikkaynak/eczane-frontend#128]
![Screenshot_2](https://user-images.githubusercontent.com/109925130/218825745-18321fd9-6795-402e-880b-95c331bed418.png)

**Comment by Onkel-Nano** [comment]
what is the expected size for mobile devices?

**Comment by okazkayasi** [comment]
This issue is in progress right now @Onkel-Nano. we would provide the Figma file otherwise.

**Comment by furkanevin** [comment]
solved in  #135 waiting for merge
