### ISSUE TITLE
feat: improve city buttons

### ISSUE THREAD

**Issue by unitythemaker** [acikkaynak/eczane-frontend#14]
![2023-02-11_22-24](https://user-images.githubusercontent.com/83316880/218277298-65ac06ca-aa7b-44df-8f5f-b783aceff522.png)
These buttons have no affect.

- Animation can be speed up or it can teleport to the location. It is a bit slow.
- There should be less margin between buttons. Maybe flex-wrap can be used.
- That feature worked recently, but while it was working it wasn't working in the list view, only worked in map.

**Comment by furkanevin** [comment]
bakıyorum

**Comment by unitythemaker** [comment]
Furkan'ın elektriği kesildi arkadaşlar, halledebilecek varsa süper olur.

**Comment by unitythemaker** [comment]
Assigned to: Oğuzhan Şenokur
