### ISSUE TITLE
Tum icon'larin svg'ye gecirilmesi

### ISSUE THREAD

**Issue by okazkayasi** [acikkaynak/eczane-frontend#160]
Az sayida icon png seklinde. svg'ye gecirelim

**Comment by okazkayasi** [comment]
@burakkp atandi.

**Comment by okazkayasi** [comment]
@onokumus'tan gelen PR merge'lendi. issue'yu açık tutoyorum yine de. @burakkp optimize etmeyi planlıyor.

**Comment by burakkp** [comment]
Tamamlandi

**Comment by okazkayasi** [comment]
Eline saglik @burakkp
