### ISSUE TITLE
bug: map/list selector breaks when clicked to the already selected option

### ISSUE THREAD

**Issue by unitythemaker** [acikkaynak/eczane-frontend#19]
# Replicating

Click "Listede Gör" then click it again. Below list of pharmacies and hospitals will stop to show up.

![Peek 2023-02-11 23-41](https://user-images.githubusercontent.com/83316880/218280316-cdee28c1-7527-4836-a2a4-dd2419660672.gif)

**Comment by furkanevin** [comment]
bakıyorum
