### ISSUE TITLE
feat: map view should expand according to display size or should be re-sizable

### ISSUE THREAD

**Issue by unitythemaker** [acikkaynak/eczane-frontend#20]
Map view height is very small, it should be resizable (dragging from bottom) or it should expand to the available space.

**Comment by cagan123-alt** [comment]
Tamamdır.Responsiveliğinin nasıl olması gerekitiğini konuşalım.Mobil ve web için haritayı daha iyi hale getirelim.Nasıl yapılıcağı ve büyüklüğü hakkındaki ve tasarımlar hakkında.

**Comment by furkanevin** [comment]
bakıyorum

**Comment by unitythemaker** [comment]
fixed in #53 waiting for merge

**Comment by unitythemaker** [comment]
marking as wontfix as this wasn't planned on the design, my bad
