### ISSUE TITLE
Don't display phone icon if there are no phone numbers

### ISSUE THREAD

**Issue by firatgomi** [acikkaynak/eczane-frontend#24]
If there is no phone number for a pharmacy, let's hide the phone icon
<img width="573" alt="image" src="https://user-images.githubusercontent.com/86969631/218282268-822285dd-1399-4deb-a6c1-97c1eab2c9f8.png">

**Comment by duyguevrim** [comment]
bakıyorum

**Comment by unitythemaker** [comment]
Fixed for list view, not fixed for map view.
