### ISSUE TITLE
Not all data show up when a city selected 

### ISSUE THREAD

**Issue by selamikarakas** [acikkaynak/eczane-frontend#28]
I clicked on Kahramanmaraş but not all data was visible on the map. Only one data in the center came. Since Kahramanmaraş is a big city with its districts, it is difficult to find the appropriate health institution by clicking the button. For example, if I was on Pazarcık and clicked Kahramanmaraş to see a health institution on there, I can not see any information related to pazarcık. Maybe two dropdown for filtering city and district can solve this problem. 
![image](https://user-images.githubusercontent.com/57862307/218284702-b22e6754-81ce-4fa8-87f6-8027e2538683.png)

**Comment by cagan123-alt** [comment]
TO DO da vardı bu dediğiniz evet iyi yakalamışsınız.Düzeltmesi il ve ilçe filtresinin liste de gösterde ve harita kısmındaki çalışırlığında şu anda sorun var.Fixleri geçilicek zaten.
