### ISSUE TITLE
Loading screen should be styled

### ISSUE THREAD

**Issue by DarkSavci** [acikkaynak/eczane-frontend#34]
![image](https://user-images.githubusercontent.com/70711866/218288701-2538a270-b8fe-4c3a-a75e-dcf7b1803cbd.png)

**Comment by cagan123-alt** [comment]
Klasik bir loadbar koymamızı mi istiyorsun.Yoksa yeni bi tasarım vs... olucak mı.Eğer klasik bi loadbar ise hemen hallederim.
