### ISSUE TITLE
enhancement: lock map scrolling button

### ISSUE THREAD

**Issue by unitythemaker** [acikkaynak/eczane-frontend#36]
For enhancing mobile experience, there should be a button for lock/unlock map scrolling.

![2023-02-12_05-28](https://user-images.githubusercontent.com/83316880/218289615-9ab23a63-e3c8-4393-bfb2-b7dce34d725c.png)
(Inspiration from [afetharitasi.org](https://afetharitasi.org/))

**Comment by cagan123-alt** [comment]
Üzerinde çalışıyorum.Bitti sayılır o buttonun dizaynı ile ilgili konuşalım sonra ekleyelim.

**Comment by unitythemaker** [comment]
fixed in #57
