### ISSUE TITLE
enhancement: responsive design

### ISSUE THREAD

**Issue by leonvea** [acikkaynak/eczane-frontend#4]
Siteye telefondan girdiğimizde her şey iç içe geçilmiş oluyor ve bir çok işlevi kullanamıyoruz , Frontend ile düzeltilebilir

![Screenshot_20230211-175115_Opera](https://user-images.githubusercontent.com/84559277/218265269-6bf6e1a1-9a37-41da-8aed-29bc7f6e7a63.jpg)

**Comment by unitythemaker** [comment]
looks like this issue is generally fixed
