### ISSUE TITLE
Address Information

### ISSUE THREAD

**Issue by selamikarakas** [acikkaynak/eczane-frontend#43]
Only some of address data shown in map view and the rest is shown on list view. There should be a details button which expand the card and shows address details.
![image](https://user-images.githubusercontent.com/57862307/218301710-38d2759a-8f59-4272-820f-187e2dc38e6b.png)

![image](https://user-images.githubusercontent.com/57862307/218301661-4e90f2cc-c99a-467e-b9a1-c39b00b4420a.png)

![image](https://user-images.githubusercontent.com/57862307/218301684-34b19b94-94b0-48a4-a70a-317834cb49ed.png)

**Comment by unitythemaker** [comment]
View details button.
Details is a pop-up.
It will show all information including extra ones such as directions information.
Pop-up will close when clicked outside.

**Comment by unitythemaker** [comment]
Assigned to: burakkp

**Comment by unitythemaker** [comment]
fixed in #55
