### ISSUE TITLE
Shorten the space between cities and card list on list view

### ISSUE THREAD

**Issue by firatgomi** [acikkaynak/eczane-frontend#44]
Currently, there is a big space between cities and the card list:
Mobile:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/86969631/218300553-7e712b59-8e6c-4500-89b0-4897f563669c.png">
Web:
<img width="1373" alt="image" src="https://user-images.githubusercontent.com/86969631/218300570-6629ec80-5d3e-45ed-a5f1-8a589a7a0467.png">
Let's reduce this size to a better standard. We can contact Mrs. Yagmur through discord for help regarding the appropriate size.

**Comment by oguzhansenokur** [comment]
The issue can be resolved by change/remove height of wrapper for 2 sections I can handle the issue.

**Comment by haksuman** [comment]
The issue has been resolved in #45, box component height defined as auto in case of future province list changes.
