### ISSUE TITLE
Image should have gradiant

### ISSUE THREAD

**Issue by DarkSavci** [acikkaynak/eczane-frontend#73]
![image](https://user-images.githubusercontent.com/70711866/218429334-b0f624bf-4945-4310-a2fe-8632cc112087.png)
Image should gradually change colors so it wont look bad

**Comment by furkanevin** [comment]
![download](https://user-images.githubusercontent.com/109925130/218448890-87607c04-2fcb-4fe5-8399-4fc8d2f3bebb.png)
