### ISSUE TITLE
Son Kartın Ortadan Sola Alınması

### ISSUE THREAD

**Issue by okazkayasi** [acikkaynak/eczane-frontend#95]
Son sıradaki kartlar sola yaslı devam etmeli

![image](https://user-images.githubusercontent.com/10429728/218778288-3110453a-184e-4ae6-8d54-6f17124237bc.png)

**Comment by halitpeker** [comment]
Bakabilirim

**Comment by okazkayasi** [comment]
Hocam bunu hallettim @halitpeker
